Stat svc
AhraAvidzba/java-explore-with-me pull request #3
Opened 2023-08-03 08:49 UTC by AhraAvidzba

2023-08-04 04:10 UTC, TomattmanYandex requested changes
лучше сделать парочку небольших изменений

2023-08-04 04:10 UTC, TomattmanYandex commented on ewm/src/main/java/ru/practicum/ewm/Main.java
> +        System.out.println("Hello world!");
эту строчку стоит удалить

2023-08-04 04:10 UTC, TomattmanYandex commented on statistic/statistic-server/src/main/java/ru/practicum/statistics/statistic/Statistic.java
> +    private LocalDateTime timestamp;
что за таймстемп, что в нем конкретно будет храниться, время создания, время изменения, время запроса?
Следует давать однозначные имена, чтобы было понятно за что отвечает переменная

2023-08-04 04:10 UTC, TomattmanYandex commented on statistic/statistic-server/src/main/java/ru/practicum/statistics/statistic/Statistic.java
> +    private LocalDateTime timestamp;
и в базе тоже

2023-08-04 04:10 UTC, TomattmanYandex commented on statistic/statistic-server/src/main/java/ru/practicum/statistics/statistic/StatisticServiceImpl.java
> +        if (uris.length == 0 && unique) {
очень тяжело понять логику этих if может лчше было бы сделать вложенные блоки
if(unique) {
  if(uris.length == 0){

  } else { 
  
  }
} else {
...

2023-08-07 13:52 UTC, AhraAvidzba commented on statistic/statistic-server/src/main/java/ru/practicum/statistics/statistic/Statistic.java
> +    private LocalDateTime timestamp;
согласен, но тесты постман требуют названия поля "timestamp"

2023-08-07 14:01 UTC, AhraAvidzba commented on statistic/statistic-server/src/main/java/ru/practicum/statistics/statistic/StatisticServiceImpl.java
> +        if (uris.length == 0 && unique) {
так получается больше строк кода, но понять действительно легче. Поменяю

2023-08-08 10:23 UTC, TomattmanYandex commented on statistic/statistic-server/src/main/java/ru/practicum/statistics/statistic/Statistic.java
> +    private LocalDateTime timestamp;
в дто оставить таймстемп, а в базе дать понятное имя))

2023-08-08 10:23 UTC, TomattmanYandex approved these changes
Принято, но про таймстемп подумай

2023-08-09 22:32 UTC, merged