Main svc
AhraAvidzba/java-explore-with-me pull request #4
Opened 2023-08-17 13:16 UTC by AhraAvidzba

2023-08-18 09:22 UTC, TomattmanYandex requested changes
Привет, вроде все хорошо, кроме момента с таблицей ивент и полем законфирмленных участников, может случаться случай, когда запрос на участие добавлен, а число в ивенте не обновится, и тогда будет проблема, надо либо использовать транзакции, чтобы избежать этого, либо убрать поле из ивента, и всегда подчитывать количество запросов

Плюс надо добавить скрипты на создание структуры базы

2023-08-18 09:22 UTC, TomattmanYandex commented on ewm/src/main/java/ru/practicum/ewm/category/CategoryControllerPublic.java
> +    public List<CategoryOutDto> getCategory(@PositiveOrZero @RequestParam(defaultValue = "0") int from,
я бы переименовал этот метод в getCategories потому что возвращаем мы все же список категорий а не одну

2023-08-18 09:22 UTC, TomattmanYandex commented on ewm/src/main/java/ru/practicum/ewm/category/CategoryControllerPublic.java
> +        log.info("Возвращаются категории");
и изменить бы немного сообщение логов, самый простой вариант, указать какой эндпоинт был вызван

2023-08-18 09:22 UTC, TomattmanYandex commented on ewm/src/main/java/ru/practicum/ewm/category/dto/CategoryInDto.java
> +public class CategoryInDto {
CategoryRequestDto читалось бы лучше

2023-08-18 09:22 UTC, TomattmanYandex commented on ewm/src/main/java/ru/practicum/ewm/event/Event.java
> +    private int confirmedRequests;
не уверен что хорошо так хранить, так ты не сможешь понять какой пользователь подтвердил участие, а какой нет, и я посылая несколько раз подтверждение ,могу полностью заполнить лимит
лучше сделать связанную таблицу с подтверждениями

2023-08-18 09:22 UTC, TomattmanYandex commented on ewm/src/main/java/ru/practicum/ewm/event/Event.java
> +    private int participantLimit;
вот тут было бы лучше использовать класс обертку, она даст больше гибкости, может быть null значение что значит никаких лимитов, а может быть реальное значение, которое как раз будет значить каков лимит

2023-08-18 10:00 UTC, AhraAvidzba commented on ewm/src/main/java/ru/practicum/ewm/event/Event.java
> +    private int confirmedRequests;
на сколько я понял спецификацию в тз поле должно хранить именно количество подтвержденных запросов. Какой пользователь уже отправлял запрос на участие в событии и другая информация хранятся в классе запросов ParticipationRequest где так же присутствует статус заявки. Возможность полностью заполнить лимит участия одним пользователем исключен, так как по спецификации в тз это необходимо проверять на этапе добавления запроса на участие. 
![Снимок экрана 2023-08-18 в 12 57 53](https://github.com/AhraAvidzba/java-explore-with-me/assets/117780055/b30e47e1-1477-4fc4-8a3d-09bde830b301) 
![Снимок экрана 2023-08-18 в 12 58 24](https://github.com/AhraAvidzba/java-explore-with-me/assets/117780055/92875855-a113-4685-a566-046f88d9c2d3)

2023-08-19 03:24 UTC, TomattmanYandex approved these changes
принято

2023-08-19 03:24 UTC, TomattmanYandex commented on ewm/src/main/java/ru/practicum/ewm/category/CategoryControllerPublic.java
> +        log.info("Возвращаются категории. Эндпоинт {}", request.getRequestURI());
можно проще 
log.info("/categories");

2023-08-19 17:57 UTC, merged